name: del

dependencies:
  - python=3.10
  - pip
  - pip:
    - pandas
    - numpy
    - matplotlib
    - seaborn
    - scikit-learn
    - tensorflow
    - tensorflow-datasets
    - jupyterlab
    - tqdm
    - torch
    - torchvision
    - torchaudio